send_command:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    command:
      required: true
      example: "PO"
      selector:
        text:
    prefix:
      selector:
        text:
    suffix:
      selector:
        text:

set_panel_lock:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    panel_lock:
      required: true
      example: "0"
      default: "0"
      selector:
        select:
          translation_key: "panel_lock"
          options:  # aiopioneer.const.PANEL_LOCK
            - "0"
            - "1"
            - "2"

set_remote_lock:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    remote_lock:
      required: true
      example: false
      selector:
        boolean:

set_dimmer:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    dimmer:
      required: true
      example: "Bright"
      default: "Brightest"
      selector:
        select:
          translation_key: "dimmer_mode"
          options:  # aiopioneer.const.DIMMER_MODES
            - "Brightest"
            - "Bright"
            - "Dark"
            - "Off"
            - "(cycle)"

set_tone_settings:
  description: Set AVR tone settings for zone
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    tone:
      description: Tone mode
      required: true
      example: "On"
      default: "Bypass"
      selector:
        select:
          translation_key: "tone_mode"
          options:  # aiopioneer.const.TONE_MODES
            - "Bypass"
            - "On"
            - "(cycle)"
    treble:
      description: Tone treble value
      example: 0
      default: 0
      selector:
        number:
          min: -6
          max: 6
          step: 1
          unit_of_measurement: dB
    bass:
      description: Tone bass value
      example: 0
      default: 0
      selector:
        number:
          min: -6
          max: 6
          step: 1
          unit_of_measurement: dB

# set_amp_settings:
#   description: Set AVR amplifier function settings for zone
#   target:
#     entity:
#       integration: pioneer_async
#       domain: media_player

select_tuner_band:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    band:
      required: true
      example: "FM"
      selector:
        select:
          translation_key: "tuner_band"
          options:  # aiopioneer.const.TunerBand
            - "FM"
            - "AM"


set_fm_tuner_frequency:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    frequency:
      required: true
      example: 106.1
      selector:
        number:
          min: 87.5
          max: 108.0
          step: 0.1
          default: 87.5
          unit_of_measurement: MHz
          mode: box

set_am_tuner_frequency:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    frequency:
      required: true
      example: 988
      selector:
        number:
          min: 530
          max: 1700
          default: 530
          step: 1  # 10KHz in the Americas, 9KHz ROW
          unit_of_measurement: kHz
          mode: box

select_tuner_preset:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    class:
      required: true
      example: "C"
      default: "A"
      selector:
        select:
          options:
            - "A"
            - "B"
            - "C"
            - "D"
            - "E"
            - "F"
            - "G"
    preset:
      required: true
      example: 5
      default: 1
      selector:
        number:
          min: 1
          max: 9
          step: 1

set_channel_levels:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    channel:
      required: true
      example: "L"
      selector:
        select:
          options:
            - "L"
            - "R"
            - "C"
            - "SL"
            - "SR"
            - "SBL"
            - "SBR"
            - "SW"
            - "LH"
            - "RH"
            - "LW"
            - "RW"
            - "TML"
            - "TMR"
            - "TFL"
            - "TFR"
            - "TRL"
            - "TRR"
            - "SW1"
            - "SW2"
            - "ALL"
    level:
      required: true
      example: 0.0
      default: 0.0
      selector:
        number:
          min: -12.0
          max: 12.0
          step: 0.5
          unit_of_measurement: dB

# set_video_settings:
#   description: Set video settings for zone
#   target:
#     entity:
#       integration: pioneer_async
#       domain: media_player

# set_dsp_settings:
#   description: Set AVR DSP settings for the amplifier
#   target:
#     entity:
#       integration: pioneer_async
#       domain: media_player

# media_control:
#   description: TODO: implement using standard media functions
#   target:
#     entity:
#       integration: pioneer_async
#       domain: media_player
