send_command:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    command:
      required: true
      example: "PO"
      selector:
        text:
    prefix:
      selector:
        text:
    suffix:
      selector:
        text:

set_tone_settings:
  description: Set AVR tone settings for zone
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    tone:
      description: Tone mode
      required: true
      example: "On"
      default: "Bypass"
      selector:
        select:
          translation_key: "tone_mode"
          options:
            - "Bypass"
            - "On"
            - "(cycle)"
    treble:
      description: Tone treble value
      example: 0
      default: 0
      selector:
        number:
          min: -6
          max: 6
          step: 1
          unit_of_measurement: dB
    bass:
      description: Tone bass value
      example: 0
      default: 0
      selector:
        number:
          min: -6
          max: 6
          step: 1
          unit_of_measurement: dB

select_tuner_band:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    band:
      required: true
      example: "FM"
      selector:
        select:
          translation_key: "tuner_band"
          options:
            - "FM"
            - "AM"


set_fm_tuner_frequency:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    frequency:
      required: true
      example: 106.1
      selector:
        number:
          min: 87.5
          max: 108.0
          step: 0.1
          default: 87.5
          unit_of_measurement: MHz
          mode: box

set_am_tuner_frequency:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    frequency:
      required: true
      example: 988
      selector:
        number:
          min: 530
          max: 1700
          default: 530
          step: 1  # 10KHz in the Americas, 9KHz ROW
          unit_of_measurement: kHz
          mode: box

select_tuner_preset:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    class:
      required: true
      example: "C"
      default: "A"
      selector:
        select:
          options:
            - "A"
            - "B"
            - "C"
            - "D"
            - "E"
            - "F"
            - "G"
    preset:
      required: true
      example: 5
      default: 1
      selector:
        number:
          min: 1
          max: 9
          step: 1

set_channel_levels:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    channel:
      required: true
      example: "L"
      selector:
        select:
          options:
            - "L"
            - "R"
            - "C"
            - "SL"
            - "SR"
            - "SBL"
            - "SBR"
            - "SW"
            - "LH"
            - "RH"
            - "LW"
            - "RW"
            - "TML"
            - "TMR"
            - "TFL"
            - "TFR"
            - "TRL"
            - "TRR"
            - "SW1"
            - "SW2"
            - "ALL"
    level:
      required: true
      example: 0.0
      default: 0.0
      selector:
        number:
          min: -12.0
          max: 12.0
          step: 0.5
          unit_of_measurement: dB

set_amp_settings:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    speaker_mode:
      example:
      selector:
        select:
          translation_key: amp_speaker_mode
          options:
            - "OFF"
            - "A"
            - "B"
            - "A+B"
    hdmi_out:
      example:
      selector:
        select:
          translation_key: amp_hdmi_out
          options:
            - "ALL"
            - "HDMI 1"
            - "HDMI 2"
    hdmi3_out:
      selector:
        boolean:
    hdmi_audio:
      example:
      selector:
        select:
          translation_key: amp_hdmi_audio
          options:
            - "AMP"
            - "PASSTHROUGH"
    pqls:
      example:
      selector:
        select:
          translation_key: amp_pqls
          options:
            - "OFF"
            - "AUTO"
    dimmer:
      example:
      selector:
        select:
          translation_key: amp_dimmer
          options:
            - "Brightest"
            - "Bright"
            - "Dark"
            - "Off"
    sleep_time:
      example: 0
      selector:
        number:
          min: 0
          max: 90
          step: 30
          unit_of_measurement: min
    mode:
      example:
      selector:
        select:
          translation_key: amp_mode
          options:
            - "AMP ON"
            - "AMP Front OFF"
            - "AMP Front & Center OFF"
            - "AMP OFF"
    panel_lock:
      example:
      selector:
        select:
          translation_key: amp_panel_lock
          options:
            - "OFF"
            - "PANEL ONLY"
            - "PANEL + VOLUME"
    remote_lock:
      selector:
        boolean:

set_video_settings:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    resolution:
      example: "AUTO"
      selector:
        select:
          translation_key: video_resolution
          options:
            - "AUTO"
            - "PURE"
            - "480/576p"
            - "720p"
            - "1080i"
            - "1080p"
            - "1080/24p"
            - "4K"
            - "4K/24p"
    converter:
      selector:
        boolean:
    pure_cinema:
      example: "AUTO"
      selector:
        select:
          translation_key: video_pure_cinema
          options:
            - "AUTO"
            - "ON"
            - "OFF"
    prog_motion:
      example: 0
      selector:
        number:
          min: -4
          max: 4
          step: 1
    stream_smoother:
      example: "OFF"
      selector:
        select:
          translation_key: video_stream_smoother
          options:
            - "OFF"
            - "ON"
            - "AUTO"
    advanced_video_adjust:
      example: "PDP"
      selector:
        select:
          translation_key: video_advanced_video_adjust
          options:
            - "PDP"
            - "LCD"
            - "FPJ"
            - "Professional"
            - "Memory"
    ynr:
      example: 0
      selector:
        number:
          min: 0
          max: 8
          step: 1
    cnr:
      example: 0
      selector:
        number:
          min: 0
          max: 8
          step: 1
    bnr:
      example: 0
      selector:
        number:
          min: 0
          max: 8
          step: 1
    mnr:
      example: 0
      selector:
        number:
          min: 0
          max: 8
          step: 1
    detail:
      example: 0
      selector:
        number:
          min: 0
          max: 8
          step: 1
    sharpness:
      example: 0
      selector:
        number:
          min: 0
          max: 8
          step: 1
    brightness:
      example: 0
      selector:
        number:
          min: -6
          max: 6
          step: 1
    contrast:
      example: 0
      selector:
        number:
          min: -6
          max: 6
          step: 1
    hue:
      example: 0
      selector:
        number:
          min: -6
          max: 6
          step: 1
    chroma:
      example: 0
      selector:
        number:
          min: -6
          max: 6
          step: 1
    black_setup:
      selector:
        boolean:
    aspect:
      example: "PASSTHROUGH"
      selector:
        select:
          translation_key: video_aspect
          options:
            - "PASSTHROUGH"
            - "NORMAL"
    super_resolution:
      example: 0
      selector:
        number:
          min: 0
          max: 3
          step: 1

set_dsp_settings:
  target:
    entity:
      integration: pioneer_async
      domain: media_player
  fields:
    mcacc_memory_set:
      example:
      selector:
        number:
          min: 1
          max: 6
          step: 1
    phase_control:
      example:
      selector:
        select:
          translation_key: dsp_phase_control
          options:
            - "off"
            - "on"
            - "full band on"
    phase_control_plus:
      example: "auto"
      selector:
        select:
          translation_key: dsp_phase_control_plus
          options:
            - "auto"
            - "0"
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
            - "9"
            - "10"
            - "11"
            - "12"
            - "13"
            - "14"
            - "15"
            - "16"
    virtual_speakers:
      example: "AUTO"
      selector:
        select:
          translation_key: dsp_virtual_speakers
          options:
            - "AUTO"
            - "MANUAL"
    virtual_sb:
      selector:
        boolean:
    virtual_height:
      selector:
        boolean:
    virtual_wide:
      selector:
        boolean:
    virtual_depth:
      example: "off"
      selector:
        select:
          translation_key: dsp_virtual_depth
          options:
            - "off"
            - "min"
            - "mid"
            - "max"
    sound_retriever:
      example:
      selector:
        boolean:
    signal_select:
      example:
      selector:
        select:
          translation_key: dsp_signal_select
          options:
            - "AUTO"
            - "ANALOG"
            - "DIGITAL"
            - "HDMI"
    input_attenuator:
      selector:
        boolean:
    eq:
      selector:
        boolean:
    standing_wave:
      selector:
        boolean:
    sound_delay:
      example: 0
      selector:
        number:
          min: 0
          max: 800
          step: 5
          unit_of_measurement: ms
    digital_noise_reduction:
      selector:
        boolean:
    dialog_enhancement:
      example: "off"
      selector:
        select:
          translation_key: dsp_dialog_enhancement
          options:
            - "off"
            - "flat"
            - "+1"
            - "+2"
            - "+3"
            - "+4"
    audio_scaler:
      example: "AUTO"
      selector:
        select:
          translation_key: dsp_audio_scaler
          options:
            - "AUTO"
            - "MANUAL"
    hi_bit:
      selector:
        boolean:
    up_sampling:
      example: "off"
      selector:
        select:
          translation_key: dsp_up_sampling
          options:
            - "off"
            - "2 times"
            - "4 times"
    digital_filter:
      example: "slow"
      selector:
        select:
          translation_key: dsp_digital_filter
          options:
            - "slow"
            - "sharp"
            - "short"
    dual_mono:
      example: "CH1+CH2"
      selector:
        select:
          translation_key: dsp_dual_mono
          options:
            - "CH1+CH2"
            - "CH1"
            - "CH2"
    fixed_pcm:
      selector:
        boolean:
    dynamic_range:
      example: "off"
      selector:
        select:
          translation_key: dsp_dynamic_range
          options:
            - "off"
            - "auto"
            - "mid"
            - "max"
    lfe_attenuator:
      example: "0"
      selector:
        select:
          translation_key: dsp_lfe_attenuator
          options:
            - "off"
            - "-20"
            - "-19"
            - "-18"
            - "-17"
            - "-16"
            - "-15"
            - "-14"
            - "-13"
            - "-12"
            - "-11"
            - "-10"
            - "-9"
            - "-8"
            - "-7"
            - "-6"
            - "-5"
            - "-4"
            - "-3"
            - "-2"
            - "-1"
            - "0"
    sacd_gain:
      example: "0"
      selector:
        select:
          translation_key: dsp_sacd_gain
          options:
            - "0"
            - "6"
    auto_delay:
      selector:
        boolean:
    center_width:
      example: 1
      selector:
        number:
          min: 1
          max: 7
          step: 1
    panorama:
      selector:
        boolean:
    dimension:
      example: 0
      selector:
        number:
          min: -3
          max: 3
          step: 1
    center_image:
      example: 0
      selector:
        number:
          min: 0
          max: 1
          step: 0.1
    effect:
      example: 10
      selector:
        number:
          min: 10
          max: 90
          step: 10
    height_gain:
      example: "low"
      selector:
        select:
          translation_key: dsp_height_gain
          options:
            - "low"
            - "mid"
            - "high"
    loudness_management:
      selector:
        boolean:
    center_spread:
      selector:
        boolean:
    rendering_mode:
      example: "object base"
      selector:
        select:
          translation_key: dsp_rendering_mode
          options:
            - "object base"
            - "channel base"

# media_control:
#   description: TODO: implement using standard media functions
#   target:
#     entity:
#       integration: pioneer_async
#       domain: media_player
